[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bmrblib"
version = "1.0.5"
authors = [
    {name = "Edward d'Auvergne", email = "edward@nmr-relax.com"},
]
description = "The BMRB library"
requires-python = ">=2.5"
keywords = ["BMRB", "BioMagResBank", "Biological Magnetic Resonance Data Bank"]
license = {text = "GPLv3+"}
classifiers = [
    "Programming Language :: Python :: 2",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "numpy",
]
homepage = [
    "https://sourceforge.net/projects/bmrblib/",
]

[tool.setuptools]
packages = [
    "bmrblib",
    "bmrblib.assembly_supercategory",
    "bmrblib.citations",
    "bmrblib.entry_information",
    "bmrblib.experimental_details",
    "bmrblib.kinetics",
    "bmrblib.NMR_parameters",
    "bmrblib.pystarlib",
    "bmrblib.structure",
    "bmrblib.thermodynamics"
]

